adding getting started guide to the docs
arcalot/arcalot.github.io pull request #19
Opened 2022-11-25 16:21 UTC by dustinblack

## Changes introduced with this PR

New "Getting Started" guide added to the core documentation.

---
By contributing to this repository, I agree to the [contribution guidelines](https://github.com/arcalot/.github/blob/main/CONTRIBUTING.md).

2022-11-25 18:11 UTC, portante requested changes
Looks good.

2022-11-25 18:11 UTC, portante commented on docs/arcaflow/getting-started.md
> +[Arcaflow](https://arcalot.io/arcaflow/) is a modular system that enables engineers to easily build complex parallelized workflows for test automation without requiring any pre-installation or deploy
The comma (",") in "architecture, together with which" seems misplaced.

2022-11-25 18:11 UTC, portante commented on docs/arcaflow/getting-started.md
> +The engine component is intended to run from your laptop, jump host, or wherever you have network connectivity to the System Under Test (SUT). No installation is required of any Arcaflow components,
s/System Under Test (SUT)/target environment/?

2022-11-25 18:11 UTC, portante commented on docs/arcaflow/getting-started.md
> +The engine component is intended to run from your laptop, jump host, or wherever you have network connectivity to the System Under Test (SUT). No installation is required of any Arcaflow components,
Perhaps you'd want to say that "the engine invokes the plugins in the target environment according to the workflow definition and passes the required data to the plugins as directed by the workflow" ... or something like that.

2022-11-28 13:42 UTC, dustinblack commented on docs/arcaflow/getting-started.md
> +[Arcaflow](https://arcalot.io/arcaflow/) is a modular system that enables engineers to easily build complex parallelized workflows for test automation without requiring any pre-installation or deploy
I disagree about the comma, but it's pretty subjective.

2022-11-28 14:49 UTC, portante requested changes

2022-11-28 19:11 UTC, jaredoconnell requested changes

2022-12-02 13:38 UTC, portante approved these changes

2022-12-02 14:33 UTC, tsebastiani approved these changes

2022-12-02 20:32 UTC, jaredoconnell approved these changes

2022-12-02 21:25 UTC, merged