Update Documentation
arcalot/arcalot.github.io pull request #55
Opened 2023-06-14 14:48 UTC by jdowni000

## Changes introduced with this PR

This is an attempt to resolve #38 . I have removed the lists and plurals from the documentation. Additionally, I have added that the annotation can be repeated if you multiple conflicts are warranted. 

---
By contributing to this repository, I agree to the [contribution guidelines](https://github.com/arcalot/.github/blob/main/CONTRIBUTING.md).

2023-06-15 18:43 UTC, jdowni000 commented on docs/arcaflow/plugins/python/data-model.md
>  - `schema.required_if` specifies a list of fields that cause the current field to be required. If the other fields are empty, the current field is not required. (Make sure to use the optional annotat
I have updated these as well. Thank you stranger! @janosdebugs

2023-06-19 10:18 UTC, dustinblack approved these changes

2023-06-19 10:20 UTC, dustinblack requested changes

2023-06-19 10:20 UTC, dustinblack commented on docs/arcaflow/plugins/python/data-model.md
>  - `schema.required_if` specifies a list of fields that cause the current field to be required. If the other fields are empty, the current field is not required. (Make sure to use the optional annotat
It looks like you got `required_if_not` but not `require_if`

2023-06-19 13:26 UTC, jdowni000 commented on docs/arcaflow/plugins/python/data-model.md
>  - `schema.required_if` specifies a list of fields that cause the current field to be required. If the other fields are empty, the current field is not required. (Make sure to use the optional annotat
Yes you are right....missed that last change with a save before the commit. Thank you, I have updated it again

2023-06-19 17:27 UTC, dustinblack approved these changes

2023-06-19 17:28 UTC, merged